apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: protonmail
  name: protonmail
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
