apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.38.0 (HEAD)
    external-dns.alpha.kubernetes.io/hostname: bridgemail.private.willpakpoy.com
  labels:
    io.kompose.service: protonmail-bridge
  name: protonmail-bridge
spec:
  type: LoadBalancer
  loadBalancerIP: 10.40.97.10
  ports:
    - name: "1025"
      port: 1025
      targetPort: 25
    - name: "1143"
      port: 1143
      targetPort: 143
  selector:
    io.kompose.service: protonmail-bridge
