apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: ikev2-vpn-data
  name: ikev2-vpn-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
