apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: vpn
  name: vpn
spec:
  ports:
    - name: "500"
      port: 500
      protocol: UDP
      targetPort: 500
    - name: "4500"
      port: 4500
      protocol: UDP
      targetPort: 4500
  selector:
    io.kompose.service: vpn
